version: "3.9"

services:
  blockchain-registry:
    build:
      context: .
      # Choose 'development' for build with dev and test dependencies
      # Remove this target or set to 'production' for build with gunicorn as WSGI
      target: development
    image: blockchain-registry:latest
    env_file: .env
    environment:
      - TZ=America/Sao_Paulo
      - ENVIRONMENT=development
    volumes:
      - ${PWD}:/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8080:8080"
    security_opt:
      - no-new-privileges
    restart: unless-stopped
    container_name: blockchain-registry
